---
- include_vars: '{{ansible_lsb.id}}.yml'

- name: Install requirements
  apt:
    name: '{{item}}'
    state: present
  with_items: '{{docker_required_packages}}'
  tags:
    - always

- name: Add the new GPG key
  apt_key:
    url: 'https://apt.dockerproject.org/gpg'
    id: '58118E89F3A912897C070ADBF76221572C52609D'
  tags:
    - always

- name: Add apt repository
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo {{ ansible_lsb.id | lower }}-{{ ansible_distribution_release }} main'
    filename: 'docker'
    update_cache: yes
  tags:
    - always

- name: Update cache
  apt:
    update_cache: yes
  tags:
    - always

- name: Install recommended packages
  apt:
    name: '{{item}}'
    state: present
  with_items: '{{docker_recommended_packages}}'
  tags:
    - recommended

- name: Install docker
  apt:
    name: docker-engine
    state: latest
    update_cache: yes
  tags:
    - always

- name: Start docker service and enable/disable it on boot
  service:
    name: docker
    state: started
    enabled: '{{docker_service_enabled}}'
  tags:
    - always

- name: Create docker group
  group:
    name: docker
  tags:
    - optional
