---
- include_vars: '{{ansible_distribution}}.yml'

- name: Remove old package | docker
  apt:
    name: docker
    state: absent
  tags:
    - always

- name: Remove old package | docker-engine
  apt:
    name: docker-engine
    state: absent
  when: ansible_lsb.id != 'Raspbian'
  tags:
    - always

- name: Install requirements
  apt:
    name: '{{item}}'
    state: present
  with_items: '{{docker_required_packages}}'
  tags:
    - always

- name: Add the new GPG key | except Raspbian
  apt_key:
    url: 'https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg'
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
  when: ansible_lsb.id != 'Raspbian'
  tags:
    - always

- name: Add the new GPG key | for Raspbian
  apt_key:
    keyserver: 'hkp://p80.pool.sks-keyservers.net:80'
    id: '58118E89F3A912897C070ADBF76221572C52609D'
  when: ansible_lsb.id == 'Raspbian'
  tags:
    - always

- name: Add apt repository | except Raspbian
  apt_repository:
    repo: 'deb [arch={% if ansible_architecture == "x86_64" %}amd64{% elif ansible_architecture == "armv7l" or ansible_architecture == "armv6l" %}armhf{%  endif %}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable'
    filename: 'docker'
    update_cache: yes
  when: ansible_lsb.id != 'Raspbian'
  tags:
    - always

- name: Add apt repository | for Raspbian
  apt_repository:
    repo: 'deb [arch=armhf] https://apt.dockerproject.org/repo raspbian-jessie main'
    filename: 'docker'
    update_cache: yes
  when: ansible_lsb.id == 'Raspbian'
  tags:
    - always

- name: Install recommended packages
  apt:
    name: '{{item}}'
    state: present
    update_cache: yes
  with_items: '{{docker_recommended_packages}}'
  tags:
    - recommended

- name: Install docker
  apt:
    name: 'docker-{% if ansible_lsb.id == "Raspbian" %}engine{% else %}ce{% endif %}'
    state: latest
    update_cache: yes
  tags:
    - always

- name: Start docker service and enable/disable it on boot
  service:
    name: docker
    state: started
    enabled: '{{docker_service_enabled}}'
  tags:
    - always

- name: Create docker group
  group:
    name: docker
  tags:
    - optional
